services:
  livebox-exporter-rs:
      image: tchapacan/livebox-exporter-rs
      container_name: livebox-exporter-rs
      command:
        - "-P"
        - ${LIVEBOX_PASSWORD:-password}
      ports:
        - 9100:9100
      restart: unless-stopped
      networks:
        - monitoring_network
      environment:
        - LIVEBOX_PASSWORD

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    networks:
      - monitoring_network

volumes:
  prom_data:

networks:
  monitoring_network:
    driver: bridge
