{
 "title": "HomeLan",
 "tags": [ "livebox" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Product",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_infos_status", "legendFormat": "{{product_class}}" }
   ]
  },
  {
   "title": "Manufacturer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_infos_status", "legendFormat": "{{manufacturer}}" }
   ]
  },
  {
   "title": "Oui",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_infos_status", "legendFormat": "{{manufacturer_oui}}" }
   ]
  },
  {
   "title": "Model name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_infos_status", "legendFormat": "{{model_name}}" }
   ]
  },
  {
   "title": "Hardware version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "livebox_infos_status", "legendFormat": "{{hardware_version}}" }
   ]
  },
  {
   "title": "Serial number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_infos_status", "legendFormat": "{{serial_number}}" }
   ]
  },
  {
   "title": "Software version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_infos_status", "legendFormat": "{{software_version}}" }
   ]
  },
  {
   "title": "Country",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_infos_status", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "IPv6 address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_wan_status", "legendFormat": "{{ipv6_address}}" }
   ]
  },
  {
   "title": "IPv4 address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_wan_status", "legendFormat": "{{ip_address}}" }
   ]
  },
  {
   "title": "Gateway",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_wan_status", "legendFormat": "{{remote_gateway}}" }
   ]
  },
  {
   "title": "Remote DNS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_wan_status", "legendFormat": "{{remote_gadns_serversteway}}" }
   ]
  },
  {
   "title": "MAC address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_wan_status", "legendFormat": "{{mac_address}}" }
   ]
  },
  {
   "title": "Link status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_link_status", "legendFormat": "{{protocol}}" }
   ]
  },
  {
   "title": "Link status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_link_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_infos_uptime", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Reboot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livebox_infos_reboot", "legendFormat": "__auto" }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "RX/TX HomeLan Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(livebox_interface_bytes_rx[$__rate_interval])",
     "legendFormat": "{{direction}} - {{interface_name}}"
    },
    {
     "expr": "rate(livebox_interface_bytes_tx[$__rate_interval])*(-1)",
     "legendFormat": "{{direction}} - {{interface_name}}"
    }
   ]
  },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Devices status",
   "type": "status-history",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "livebox_device_status", "legendFormat": "{{device_name}}" }
   ]
  }
 ]
}